// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SevkiyatBildirimApi.Data;

#nullable disable

namespace SevkiyatBildirimApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260131154936_AddRecipientsToReport")]
    partial class AddRecipientsToReport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SevkiyatBildirimApi.Models.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("EmailLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Rapor No: SK-2026-000001\nMağaza: IST001\nTPL No: TPL20260125001\nİrsaliye No: WB123456\n\nEksik Ürünler:\n- PRD001: Ürün A (Miktar: 5)\n- PRD002: Ürün B (Miktar: 3)\n\nNotlar: İlk sevkiyat eksik ürün bildirimi",
                            CreatedAt = new DateTime(2026, 1, 21, 11, 0, 0, 0, DateTimeKind.Utc),
                            ReportId = 1,
                            SentAt = new DateTime(2026, 1, 21, 11, 0, 0, 0, DateTimeKind.Utc),
                            Subject = "SK-2026-000001 | Eksik Ürün Bildirimi | TPL TPL20260125001 | Mağaza IST001",
                            To = "lojistik@example.com"
                        },
                        new
                        {
                            Id = 2,
                            Body = "Rapor No: SK-2026-000002\nMağaza: IST001\nTPL No: TPL20260126001\nİrsaliye No: WB123457\n\nHasarlı Ürünler:\n- PRD003: Ürün C (Miktar: 2, Hasar: Kırık)\n\nNotlar: Hasarlı ürün talebi reddedildi, eksik bilgi var",
                            CreatedAt = new DateTime(2026, 1, 23, 15, 0, 0, 0, DateTimeKind.Utc),
                            ReportId = 2,
                            SentAt = new DateTime(2026, 1, 23, 15, 0, 0, 0, DateTimeKind.Utc),
                            Subject = "SK-2026-000002 | Hasarlı Ürün Bildirimi | TPL TPL20260126001 | Mağaza IST001",
                            To = "lojistik@example.com"
                        });
                });

            modelBuilder.Entity("SevkiyatBildirimApi.Models.MagicLinkToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("MagicLinkTokens");
                });

            modelBuilder.Entity("SevkiyatBildirimApi.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Recipients")
                        .HasColumnType("text");

                    b.Property<string>("ReportNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ResendCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TplNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WaybillNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ReportNo")
                        .IsUnique();

                    b.HasIndex("ShipmentDate");

                    b.HasIndex("Status");

                    b.HasIndex("StoreCode");

                    b.HasIndex("TplNo");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Notes = "İlk sevkiyat eksik ürün bildirimi",
                            ReportNo = "SK-2026-000001",
                            ResendCount = 0,
                            ShipmentDate = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Sent",
                            StoreCode = "IST001",
                            TplNo = "TPL20260125001",
                            Type = "Missing",
                            UpdatedAt = new DateTime(2026, 1, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            WaybillNo = "WB123456"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 23, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Notes = "Hasarlı ürün talebi reddedildi, eksik bilgi var",
                            ReportNo = "SK-2026-000002",
                            ResendCount = 0,
                            ShipmentDate = new DateTime(2026, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Rejected",
                            StoreCode = "IST001",
                            TplNo = "TPL20260126001",
                            Type = "Damaged",
                            UpdatedAt = new DateTime(2026, 1, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            WaybillNo = "WB123457"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Notes = "Taslak bildirim",
                            ReportNo = "SK-2026-000003",
                            ResendCount = 0,
                            ShipmentDate = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Draft",
                            StoreCode = "IST001",
                            TplNo = "TPL20260131001",
                            Type = "Missing",
                            UpdatedAt = new DateTime(2026, 1, 26, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SevkiyatBildirimApi.Models.ReportAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ActorId")
                        .HasColumnType("integer");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportActions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionType = "CREATED",
                            ActorId = 1,
                            ActorName = "Mağaza Müdürü",
                            CreatedAt = new DateTime(2026, 1, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            Message = "Rapor oluşturuldu",
                            ReportId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActionType = "SENT",
                            ActorId = 1,
                            ActorName = "Mağaza Müdürü",
                            CreatedAt = new DateTime(2026, 1, 21, 11, 0, 0, 0, DateTimeKind.Utc),
                            Message = "Email gönderildi",
                            ReportId = 1
                        },
                        new
                        {
                            Id = 3,
                            ActionType = "CREATED",
                            ActorId = 2,
                            ActorName = "Mağaza Yardımcısı",
                            CreatedAt = new DateTime(2026, 1, 23, 14, 0, 0, 0, DateTimeKind.Utc),
                            Message = "Rapor oluşturuldu",
                            ReportId = 2
                        },
                        new
                        {
                            Id = 4,
                            ActionType = "SENT",
                            ActorId = 2,
                            ActorName = "Mağaza Yardımcısı",
                            CreatedAt = new DateTime(2026, 1, 23, 15, 0, 0, 0, DateTimeKind.Utc),
                            Message = "Email gönderildi",
                            ReportId = 2
                        },
                        new
                        {
                            Id = 5,
                            ActionType = "REJECTED",
                            ActorId = 2,
                            ActorName = "Mağaza Yardımcısı",
                            CreatedAt = new DateTime(2026, 1, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            Message = "Red sebebi: Fotoğraf eksik",
                            ReportId = 2
                        },
                        new
                        {
                            Id = 6,
                            ActionType = "CREATED",
                            ActorId = 1,
                            ActorName = "Mağaza Müdürü",
                            CreatedAt = new DateTime(2026, 1, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            Message = "Rapor oluşturuldu",
                            ReportId = 3
                        });
                });

            modelBuilder.Entity("SevkiyatBildirimApi.Models.ReportItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DamageType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProductNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductNo");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProductName = "Ürün A",
                            ProductNo = "PRD001",
                            Qty = 5,
                            ReportId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProductName = "Ürün B",
                            ProductNo = "PRD002",
                            Qty = 3,
                            ReportId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 23, 14, 0, 0, 0, DateTimeKind.Utc),
                            DamageType = "Kırık",
                            ProductName = "Ürün C",
                            ProductNo = "PRD003",
                            Qty = 2,
                            ReportId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            ProductName = "Ürün D",
                            ProductNo = "PRD004",
                            Qty = 10,
                            ReportId = 3
                        });
                });

            modelBuilder.Entity("SevkiyatBildirimApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StoreCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProviderId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Mağaza Müdürü",
                            Email = "manager@demo.com",
                            PasswordHash = "$2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
                            Provider = 0,
                            Role = "Manager",
                            StoreCode = "IST001"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Mağaza Yardımcısı",
                            Email = "assistant@demo.com",
                            PasswordHash = "$2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
                            Provider = 0,
                            Role = "Assistant",
                            StoreCode = "IST001"
                        });
                });

            modelBuilder.Entity("SevkiyatBildirimApi.Models.EmailLog", b =>
                {
                    b.HasOne("SevkiyatBildirimApi.Models.Report", "Report")
                        .WithMany("EmailLogs")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("SevkiyatBildirimApi.Models.Report", b =>
                {
                    b.HasOne("SevkiyatBildirimApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SevkiyatBildirimApi.Models.ReportAction", b =>
                {
                    b.HasOne("SevkiyatBildirimApi.Models.Report", "Report")
                        .WithMany("Actions")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("SevkiyatBildirimApi.Models.ReportItem", b =>
                {
                    b.HasOne("SevkiyatBildirimApi.Models.Report", "Report")
                        .WithMany("Items")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("SevkiyatBildirimApi.Models.Report", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("EmailLogs");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
